"""init

Revision ID: fb0e77c10b3e
Revises: 
Create Date: 2020-12-03 16:57:45.544786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb0e77c10b3e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receiver',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('birthday', sa.DateTime(), nullable=True),
    sa.Column('arrival', sa.DateTime(), nullable=True),
    sa.Column('needed_organ', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('abo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receiver')
    # ### end Alembic commands ###
